### ISSUE TITLE
Parse failure involving trailing-colon hash key and newline

### ISSUE THREAD

**Issue by dschweisguth** [seattlerb/debride#12]
```
$ ruby --version
ruby 2.1.6p336 (2015-04-13 revision 50298) [x86_64-darwin14.0]
$ gem list | grep debride
debride (1.3.0)
$ cat x.rb 
class X
  def x
    { key:
      :value }
  end
end
$ debride x.rb 
  skipping x.rb: Odd number (2) list for Hash. s(:array, s(:call, nil, :key))
These methods MIGHT not be called:
# end of output
```

Replacing `key:` with `:key =>` or removing the newline after `key:` fixes the error.

**Comment by zenspider** [comment]
Can you refile both of these under ruby_parser?

**Comment by dschweisguth** [comment]
https://github.com/seattlerb/ruby_parser/issues/188

**Comment by dschweisguth** [comment]
Confirmed that installing ruby_parser from current source fixes this issue. Thanks!

**Comment by dschweisguth** [comment]
debride now makes it all the way through our 200K LOC Rails app. Long output, but I think I see some ponies in there already. Many thanks!

**Comment by zenspider** [comment]
Pleeeeeease take notes! Or give me access to the commits. I'll sign an nda so long as I can publish anonymous numbers.

**Comment by schwagogo** [comment]
Here are some notes:
Rails 3 app, will turn 8 years old on May 9, ~200K LOC, ~91% covered by tests, most unused methods revealed by lack of test coverage already removed from production (non-test) code. We don't measure coverage of test code so it would not be surprising to find some unused methods there.

debride (actually `debride -r app lib`) found ~1300 possibly unused methods. I had to ignore the output for Rails controllers and helpers, since only our logs know whether actions are used or unused, and debride doesn't detect method usages in erb. That left lib, models and what Rails 4 would call concerns (classes supporting controllers and models), ~800 possibly unused methods. It took me a couple of hours (in the air between Atlanta and SF) to review them. I found ~30 unused methods, almost all tested but not used in actual application code. A few unused methods were untested one-liners that hadn't stood out in coverage.

I also found around a dozen methods in production code that were only used in test code. I inlined a few but otherwise ignored them; a more exacting team might take the time to move them to test code.

debride found ~50 unused methods in our test code, and about half were unused.

Total lines of code removed (unused production code, tests of that unused production code, and unused test code): ~1200. No effect on coverage, since almost all of the removed code was tested or was in test code, which we don't include in the coverage measurement.

**Comment by zenspider** [comment]
@schwagogo can you file this comment in its own ticket so I can more easily find it?

**Comment by zenspider** [comment]
Closing. Release of ruby_parser coming soon(ish).

**Comment by dschweisguth** [comment]
Moved report of results to https://github.com/seattlerb/debride/issues/13. Removed original comment here since I made it under the wrong account.
