### ISSUE TITLE
Using namespaces / classes for the whitelist?

### ISSUE THREAD

**Issue by troessner** [seattlerb/debride#23]
I'd love to integrate `debride` into the (Reek)[https://github.com/troessner/reek] build process.
Unfortunately I encountered a problem with the whitelist feature.
As ar as I can see (here)[https://github.com/seattlerb/debride/blob/master/lib/debride.rb#L365] it seems like the whitelist is expected to consist of method names only which means that if I have 3 methods called "foobar" in 3 completely different classes I can only whitelist all of them.

Any chance you're interested in making this more configurable so we can actually use something like this:

> > My::Namespace::Klazz#foobar

in the whitelist?

**Comment by zenspider** [comment]
Hey!

The problem is that a message send is a message send. Debride, doing naive static analysis without variable tracing can't (necessarily) know what class is getting the message send. The whitelist basically just says "consider these messages sent already".

Adding the ability to whitelist a specific class/module + method name is not out of the question... Not sure  _how_ it would work at this point. `known` maps method name to an array of classes. Your notation above (my preference) would have to be broken down to selectively delete that particular class from that method's array. Yeah... that sounds about right.

Be sure to also take a look at `bin/debride_rails_whitelist`. Might help a bit on the noise (on rails projects, obviously).

**Comment by troessner** [comment]
>>Be sure to also take a look at bin/debride_rails_whitelist. Might help a bit on the noise (on rails projects, obviously).

I'll check that out, thanks!

Closing this one.

**Comment by zenspider** [comment]
Why close?

**Comment by troessner** [comment]
>> Why close?

I have not checked out bin/debride_rails_whitelist yet, but I assumed that, given that we don't know what type a variable has at analysis time, what I'd like to do is kind of impossible. Unless we try to infer the type which is probably way out of the scope of this gem.

Or am I missing something?

**Comment by zenspider** [comment]
Reopening. I think there is more to discuss/pursue.

**Comment by zenspider** [comment]
Reopening. I think there is more to discuss/pursue.

**Comment by zenspider** [comment]
Reopening. I think there is more to discuss/pursue.

**Comment by zenspider** [comment]
7 years, no discussion... sooo yeah, let's close.
